# streamlit run C:\Data\Job\UK\Zencargo\phase4_streamlit_review.py
import streamlit as st
import pandas as pd
import os

# ========== Load Data ==========
file_path = r"C:\Data\Job\UK\Zencargo\phase3_final_enriched_output.csv"
output_path = r"C:\Data\Job\UK\Zencargo\phase4_reviewed_output.csv"

st.set_page_config(page_title="HS Code Review", layout="wide")

st.title("📦 HS Code Review Interface")
st.write("Review and confirm or edit HS code predictions generated by the LLM + Rule-based system.")

if not os.path.exists(file_path):
    st.error(f"File not found: {file_path}")
    st.stop()

df = pd.read_csv(file_path)
df["approved_hs_code"] = df["final_hs_code"]
df["manual_note"] = ""

# ========== Interactive Table ==========
edited_rows = []

for idx, row in df.iterrows():
    st.markdown("---")
    st.subheader(f"SKU: {row['sku_code']}")
    st.text(f"Description: {row['product_description']}")

    with st.expander("📤 LLM Response"):
        st.code(row.get("llm_response", ""), language="text")

    with st.expander("🧠 Rule-Based Fallback"):
        st.code(row.get("fallback_hs_code", ""), language="text")

    default_code = row["final_hs_code"]
    new_code = st.text_input(f"✅ Final HS Code for SKU {row['sku_code']}", value=default_code, key=f"hs_{idx}")
    note = st.text_input(f"📝 Note / Reason (optional)", value="", key=f"note_{idx}")

    df.at[idx, "approved_hs_code"] = new_code.strip()
    df.at[idx, "manual_note"] = note.strip()

# ========== Save Button ==========
if st.button("💾 Save Reviewed Results"):
    df.to_csv(output_path, index=False)
    st.success(f"Saved reviewed data to: {output_path}")
